ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # KRİTİK AYAR 1: Odometri/GPS gelmese bile ilk IMU paketiyle odom TF'ini başlatır
    predict_to_current_time: true
    permit_corrected_publication: false

    # 1. navsat_transform_node tarafından üretilen GPS metre pozisyonu
    odom0: /odometry/gps
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    # 2. GPS Hızı
    twist0: /gps/fix_velocity
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  false, false,
                    false, false, false,
                    false, false, false]
    twist0_differential: false
    twist0_relative: false
    twist0_queue_size: 10

    # 3. IMU
    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,     # Roll, Pitch, Yaw
                  false, false, false,
                  false, false, false,    # dYaw'ı false yapın
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: false
    imu0_queue_size: 10

navsat_transform:
  ros__parameters:
    frequency: 10.0
    delay: 1.0
    magnetic_declination_radians: 0.10
    yaw_offset: 1.5707963
    zero_altitude: true
    broadcast_cartesian_transform: false
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false